#spring 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://59.110.124.160:3306/monitor?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Lisuo@2018
    driver-class-name: com.mysql.jdbc.Driver
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    maxActive: 10
    max-wait: 60000
    minIdle: 5
    initial-size: 5

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialec
#mybatisPlus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.monitor.*.entity
  global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      db-column-underline: true
      dbColumnUnderline: true
      isCapitalMode: true
      refresh-mapper: true
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
      map-underscore-to-camel-case: true
      mapUnderscoreToCamelCase: true
      cache-enabled: true
logging:
  level:
    mapper: debug


#redis配置
redis:
  host: 59.110.124.160
  port: 6379
  password: lisuo@2018
  # 连接超时时间（毫秒）
  timeout: 10000
  jedis:
      pool:
         # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
