server:
    session-timeout: 1800
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    servlet:
        context-path: /monitor
spring:
  jackson:
    time-zone: GMT+8
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  devtools:
    restart:
      enabled: true
  thymeleaf:
     mode: HTML
     cache: false
     suffix: .html
